//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meetup.WebApi.LoadTest
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Newtonsoft.Json;

    [Priority(0)]
    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest("http://cwiazgateway.azurewebsites.net/v0/Account/register");
            request1.Timeout = 60;
            request1.Method = "POST";
            request1.Headers.Add(new WebTestRequestHeader("Origin", "http://cwiazgateway.azurewebsites.net"));
            request1.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json-patch+json"));
            request1.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            StringHttpBody request1Body = new StringHttpBody();
            request1Body.ContentType = "application/json-patch+json";
            request1Body.InsertByteOrderMark = false;
            var name = Guid.NewGuid().ToString().Replace("-", string.Empty);
            var email = $"{name}@meetup.com.br";
            var password = "123456";

            request1Body.BodyString = JsonConvert.SerializeObject(new { name, email, password });
            request1.Body = request1Body;
            yield return request1;
            request1 = null;
        }
    }
}
